[character]
success_symbol = "[▲](bold purple)"
error_symbol = "[▲](bold red)"

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "
