#!/bin/bash

set -e

success() {
  printf "\\033[32m ✔ \\033[0m\\n"
}

fail() {
  printf "\\n\\033[31m ✖ \\033[0m $1\\n"
  exit 1
}

doing() {
  printf "\\033[33m ➜ \\033[0m $1"
}

success_msg() {
  printf "\\033[33m ➜ \\033[0m $1 \\033[32m ✔ \\033[0m\\n"
}

