#!/bin/bash

set -e

success () {
  printf "\\033[32m ✔ \\033[0m\\n"
}

fail () {
  printf "\\n\\033[31m ✖ \\033[0m $1\\n"
  exit 1
}

doing () {
  printf "\\033[33m ➜ \\033[0m $1"
}

success_msg () {
  printf "\\033[33m ➜ \\033[0m $1 \\033[32m ✔ \\033[0m\\n"
}

key_missing () {
  [[ `apt-key list 2> /dev/null |\
    grep -i $1` ]]\
    && return 1 || return 0
}

repo_missing () {
  [[ `find /etc/apt/ -name '*.list' |\
    xargs cat |\
    grep '^[[:space:]]*deb' |\
    grep "$1"` ]]\
    && return 1 || return 0
}
