#!/bin/bash
# Setup VSCodium with extensions
#
# Usage: curl -fsSL sh.mohitsingh.in/code | bash

sudo echo ""

source /dev/stdin <<<"$(curl -fsSL sh.mohitsingh.in/_utils)"

# install dotfiles if not found
DOTLOC="$HOME/Projects/configs/dotfiles"
if [[ ! -d $DOTLOC ]]; then
  source /dev/stdin <<<"$(curl -fsSL sh.mohitsingh.in/repo)"
fi

# VSCodium extensions
extensions=(
  \  be5invis.vscode-custom-css
  \  bradlc.vscode-tailwindcss
  \  bradymholt.pgformatter
  \  bungcip.better-toml
  \  christian-kohler.npm-intellisense
  \  christian-kohler.path-intellisense
  \  csstools.postcss
  \  dbaeumer.vscode-eslint
  \  EditorConfig.EditorConfig
  \  enkia.tokyo-night
  \  esbenp.prettier-vscode
  \  file-icons.file-icons
  \  firefox-devtools.vscode-firefox-debug
  \  foxundermoon.shell-format
  \  GitHub.github-vscode-theme
  \  github.vscode-github-actions
  \  GitHub.vscode-pull-request-github
  \  golang.go
  \  GraphQL.vscode-graphql
  \  GraphQL.vscode-graphql-syntax
  \  JohnnyMorganz.stylua
  \  mikestead.dotenv
  \  mohitsingh.repo
  \  ms-azuretools.vscode-docker
  \  ms-python.black-formatter
  \  ms-python.flake8
  \  ms-python.isort
  \  ms-python.pylint
  \  ms-python.python
  \  ms-python.vscode-pylance
  \  ms-toolsai.jupyter
  \  ms-toolsai.jupyter-keymap
  \  ms-toolsai.jupyter-renderers
  \  ms-toolsai.vscode-jupyter-cell-tags
  \  ms-toolsai.vscode-jupyter-slideshow
  \  naumovs.color-highlight
  \  Orta.vscode-jest
  \  pflannery.vscode-versionlens
  \  redhat.vscode-xml
  \  redhat.vscode-yaml
  \  rust-lang.rust-analyzer
  \  SirTobi.pegjs-language
  \  streetsidesoftware.code-spell-checker
  \  tamasfe.even-better-toml
  \  timonwong.shellcheck
  \  usernamehw.errorlens
  \  vadimcn.vscode-lldb
  \  XadillaX.viml
  \  zxh404.vscode-proto3
  \ )

function link_config {
  # user location
  CONFIG_PATH="$HOME/.config/VSCodium"
  USER_PATH="$CONFIG_PATH/User"
  # Link config
  doing "Linking VSCodium config..."
  mkdir -p "$USER_PATH"
  ln -sf "$DOTLOC/code/settings.json" "$USER_PATH/settings.json"

  success
}

function install_extensions {
  # Install vscode extensions
  doing "Installing VSCodium extensions...\\n"
  for ext in ${extensions[*]}; do
    printf "\\033[2m      Installing %s\\033[0m" "$ext"
    codium --install-extension "$ext" >/dev/null
    # clear current line
    printf "\\r\\033[K"
  done
  # move cursor to end of previous line
  printf "\\033[1A\\033[37C"
  success
}

link_config
install_extensions
