#!/bin/bash
# Setup VSCodium with extensions
#
# Usage: curl -fsSL sh.mohitsingh.in/code | bash

sudo echo ""

source /dev/stdin <<<"$(curl -fsSL sh.mohitsingh.in/_utils)"

# install dotfiles if not found
DOTLOC="$HOME/Projects/dotfiles"
if [[ ! -d $DOTLOC ]]; then
  source /dev/stdin <<<"$(curl -fsSL sh.mohitsingh.in/repo)"
fi

# VSCodium extensions
extensions=(
  \  be5invis.vscode-custom-css
  \  bradlc.vscode-tailwindcss
  \  bradymholt.pgformatter
  \  bungcip.better-toml
  \  christian-kohler.npm-intellisense
  \  christian-kohler.path-intellisense
  \  csstools.postcss
  \  dbaeumer.vscode-eslint
  \  EditorConfig.EditorConfig
  \  enkia.tokyo-night
  \  esbenp.prettier-vscode
  \  file-icons.file-icons
  \  firefox-devtools.vscode-firefox-debug
  \  foxundermoon.shell-format
  \  golang.go
  \  GraphQL.vscode-graphql
  \  GraphQL.vscode-graphql-syntax
  \  mikestead.dotenv
  \  mohitsingh.markdoc
  \  mohitsingh.repo
  \  ms-python.isort
  \  ms-python.python
  \  ms-python.vscode-pylance
  \  naumovs.color-highlight
  \  Orta.vscode-jest
  \  pflannery.vscode-versionlens
  \  redhat.vscode-xml
  \  redhat.vscode-yaml
  \  rust-lang.rust-analyzer
  \  SirTobi.pegjs-language
  \  streetsidesoftware.code-spell-checker
  \  sumneko.lua
  \  tamasfe.even-better-toml
  \  usernamehw.errorlens
  \  vadimcn.vscode-lldb
  \  XadillaX.viml
  \  zxh404.vscode-proto3
  \ )

function install_code {
  # user location
  CONFIG_PATH="$HOME/.config/VSCodium"
  USER_PATH="$CONFIG_PATH/User"

  doing "Verifying VSCodium version..."
  VSC_ENDPOINT="https://api.github.com/repos/VSCodium/vscodium/releases/latest"
  VSC_LOCAL=$(codium --version 2>/dev/null | head -n 1)
  VSC_LATEST=$(curl -sL $VSC_ENDPOINT | jq -r '.tag_name')
  success
  if [[ "$VSC_LATEST" == "$VSC_LOCAL" ]]; then
    success_msg "Latest VSCodium is installed ( v$VSC_LATEST )"
  else
    doing "Installing VSCodium v$VSC_LATEST"
    VSC_URL=$(curl -sL $VSC_ENDPOINT | jq -r '.assets[].browser_download_url | select(endswith("amd64.deb"))')
    curl -sL "$VSC_URL" -o vscodium.deb
    sudo dpkg -i vscodium.deb
    rm vscodium.deb
    success
  fi
}

function link_config {
  # Link config
  doing "Linking VSCodium config..."
  mkdir -p "$USER_PATH"
  [[ -e "$USER_PATH/settings.json" ]] && rm "$USER_PATH/settings.json"
  [[ -e "$CONFIG_PATH/product.json" ]] && rm "$CONFIG_PATH/product.json"
  ln -s "$DOTLOC/code/settings.json" "$USER_PATH/settings.json"
  ln -s "$DOTLOC/code/product.json" "$CONFIG_PATH/product.json"
  success
}

function install_extensions {
  # Install vscode extensions
  doing "Installing VSCodium extensions...\\n"
  for ext in ${extensions[*]}; do
    printf "\\033[2m      Installing %s\\033[0m" "$ext"
    codium --install-extension "$ext" >/dev/null
    # clear current line
    printf "\\r\\033[K"
  done
  # move cursor to end of previous line
  printf "\\033[1A\\033[35C"
  success
}

install_code
link_config
install_extensions
