#!/bin/bash
# Setup mysql, postgresql and mongodb
#
# Usage: curl -fsSL sh.mohitsingh.in/databases

source /dev/stdin <<< "`curl -fsSL sh.mohitsingh.in/_utils`"

# add mongodb key and repo if missing
[[ `key_missing "mongodb"` ]] && wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
[[ `repo_missing` "mongodb" ]] && echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu `lsb_release -cs`/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list

# update and upgrade
sudo apt-get update
sudo apt-get -y upgrade

# install out databases
sudo apt-get install -y\
  mysql-server\
  postgresql\
  postgresql-contrib\
  mongodb-org
