#!/bin/bash
# Setup mysql and postgresql
#
# Usage: curl -fsSL sh.mohitsingh.in/databases | bash

source /dev/stdin <<< "`curl -fsSL sh.mohitsingh.in/_utils`"

# update and upgrade
sudo apt-get update
sudo apt-get -y upgrade

# install out databases
sudo apt-get install -y\
  mysql-server\
  postgresql\
  postgresql-contrib
