#!/usr/bin/env bash
# clone server scripts
git clone https://github.com/mohitsinghs/junkyard.git --depth=1
# create a directory for it
mkdir -p scripts/s
# copy cloned scripts to directory
mv junkyard/ubuntu/scripts/* scripts/s
# remove cloned
rm -rf junkyard
# remove itself
rm -- "$0"
