#!/bin/bash
# Setup docker
#
# Usage: curl -fsSL sh.mohitsingh.in/docker | bash

source /dev/stdin <<< "`curl -fsSL sh.mohitsingh.in/_utils`"

# Install docker
sudo apt-get update -y
key_missing "docker" && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
repo_missing "docker" && sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update -y
sudo apt-get install -y docker-ce docker-ce-cli containerd.io
sudo usermod -aG docker `whoami`
