#!/bin/bash
# Setup docker and docker-compose
#
# Usage: curl -fsSL sh.mohitsingh.in/docker | bash

source /dev/stdin <<< "`curl -fsSL sh.mohitsingh.in/_utils`"

# Install docker
sudo apt-get remove docker docker-engine docker.io containerd runc
sudo apt-get update -y
key_missing "docker" && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
repo_missing "docker" && sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update -y
sudo apt-get install -y docker-ce docker-ce-cli containerd.io
sudo usermod -aG docker `whoami`

# Install docker-compose
COMPOSE_URL=`curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r '.assets[].browser_download_url | select(endswith("Linux-x86_64"))'`
sudo curl -L $COMPOSE_URL -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
