#!/bin/bash
# Bump server limits to handle high load
#
# Usage: curl -fsSL sh.mohitsingh.in/highload | bash

# max file handles allocated
sudo sysctl -w fs.file-max=11000000
# max file handles opened
sudo sysctl -w fs.nr_open=11000000
# max buffer-space that can be allocated
sudo sysctl -w net.ipv4.tcp_mem="100000000 100000000 100000000"
# no of incoming connections
sudo sysctl -w net.core.somaxconn=10000
# no. of incoming connections backlog
sudo sysctl -w net.ipv4.tcp_max_syn_backlog=10000
# local tcp port range
sudo sysctl -w net.ipv4.ip_local_port_range="1024 65535"
