#!/bin/bash
# Bootstrap a system with my configs
#
# Usage: curl -fsSL sh.mohitsingh.in | bash

source /dev/stdin <<< "`curl -fsSL sh.mohitsingh.in/_utils`"

DOTLOC="$HOME/Projects/dotfiles"
# Grab dotfiles if not found
if [[ ! -d $DOTLOC ]]; then
  source /dev/stdin <<< "`curl -fsSL sh.mohitsingh.in/repo`"
fi

for step in essential shell vim docker databases go node
do
  source /dev/stdin <<< "`curl -fsSL sh.mohitsingh.in/$step`"
done
