#!/usr/bin/env bash

DOTLOC="$HOME/Projects/dotfiles"

# Include utilities
source /dev/stdin <<< "`curl -fsSL sh.mohitsingh.in/_utils`"

# Grab dotfiles if not found
if [[ ! -d $DOTLOC ]]; then
  source /dev/stdin <<< "`curl -fsSL sh.mohitsingh.in/repo`"
fi

# Setup homebrew
source /dev/stdin <<< "`curl -fsSL sh.mohitsingh.in/brew`"

# Setup zsh with git and tmux
source /dev/stdin <<< "`curl -fsSL sh.mohitsingh.in/shell`"

# Setup neovim with coc.nvim and other extensions
source /dev/stdin <<< "`curl -fsSL sh.mohitsingh.in/vim`"
