#!/bin/bash
# Install/Update kubectl, minikube, terraform and helm
#
# Usage : curl -fsSL sh.mohitsingh.in/kube | bash

source /dev/stdin <<< "`curl -fsSL sh.mohitsingh.in/_utils`"

# Install kubectl
doing "Verifying kubectl version"
K_LATEST=`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt | cut -b 2-`
K_LOCAL=`kubectl version -o json 2>/dev/null | jq -r '.clientVersion.gitVersion' | cut -b 2-`
success
if [[ "$K_LATEST" == "$K_LOCAL" ]]; then
  success_msg "Latest version of kubectl is already installed"
else
  doing "Downloading kubectl v$K_LATEST..."
  wget -cq "https://storage.googleapis.com/kubernetes-release/release/$(K_LATEST)/bin/linux/amd64/kubectl"
  success
  doing "Installing kubectl v$K_LATEST..."
  sudo install kubectl /usr/local/bin/kubectl
  sudo rm kubectl
  success
fi

# Install helm
key_missing  "helm" && curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
repo_missing "helm" && sudo apt-add-repository "deb https://baltocdn.com/helm/stable/debian/ all main"
sudo apt-get update -y
sudo apt-get install helm

# Install terraform and terraform-ls
key_missing "hashicorp" && curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
repo_missing "hashicorp" && sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
sudo apt-get update -y
sudo apt-get install -y terraform terraform-ls

