#!/bin/bash
# Setup nodejs 16 and yarn
#
# Usage: curl -fsSL sh.mohitsingh.in/node | bash

sudo echo ""

curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo apt-get update
sudo apt-get install -y nodejs

sudo npm i -g \
	@mohitsingh/eslint-config \
	@rushstack/eslint-patch \
	eslint \
	neovim \
	typescript \
	serve \
	surge \
	vsce
