#!/bin/bash
# Ensure that dotfiles exists

DOTLOC="$HOME/Projects/configs/dotfiles"

source /dev/stdin <<<"$(curl -fsSL sh.mohitsingh.in/_utils)"

doing "Ensuring dotfiles..."
if [[ ! -d $DOTLOC ]]; then
  # create dotfiles directory and clone
  [[ ! -d "$HOME/Projects/configs" ]] && mkdir -p "$HOME/Projects/configs"
  if [[ ! -x "$(command -v git)" ]]; then
    sudo apt-get install -y git
  fi
  git clone -q https://github.com/mohitsinghs/dotfiles.git "$DOTLOC"
fi
success
