#!/usr/bin/env bash

# define variables
DOTLOC="$HOME/Projects/dotfiles"

# Include utilities
source /dev/stdin <<< "`curl -fsSL sh.mohitsingh.in/_utils`"

# exit if macos is not found
doing "Checking system..."
if [[ $(uname) != 'Darwin' ]]; then
  fail "You are not on a mac."
else
  success
fi

# exit if dotfiles exists
doing "Ensuring dotfiles..."
if [[ ! -d $DOTLOC ]]; then
  # create dotfiles directory and clone
  [[ ! -d "$HOME/Projects" ]] && mkdir -p "$HOME/Projects"
  if [[ ! -x "$(command -v git)" ]]; then
    git clone -q https://github.com/mohitsinghs/dotfiles.git "$DOTLOC"
  fi
fi
success
