#!/usr/bin/env bash

# define variables
DOTLOC="$HOME/Projects/dotfiles"

# Include utilities
source /dev/stdin <<< "`curl -fsSL sh.mohitsingh.in/_utils`"

# exit if macos is not found
doing "Checking system..."
if [[ $(uname) != 'Darwin' ]]; then
  fail "You are not on a mac."
else
  success
fi

# exit if dotfiles exists
doing "Looking for dotfiles..."
if [[ -d  $DOTLOC ]]; then
  fail "\\033[2m$HOME/dotfiles\\033[0m already exists."
else
  success
fi

# create dotfiles directory and clone
doing "Fetching dotfiles..."
[[ ! -d "$HOME/Projects" ]] && mkdir -p "$HOME/Projects"
if [[ ! -x "$(command -v git)" ]]; then
  git clone -q https://github.com/mohitsinghs/dotfiles.git "$DOTLOC"
fi
success
