#!/usr/bin/env bash

# define variables
FUNPATH=/usr/local/share/zsh/site-functions
DOTLOC="$HOME/Projects/dotfiles"
COC_EXT_PATH="$HOME/.config/coc/extensions"

# Include utilities
source /dev/stdin <<< "`curl -fsSL sh.mohitsingh.in/_utils`"

# Install dotfiles if not found
if [[ ! -d $DOTLOC ]]; then
  source /dev/stdin <<< "`curl -fsSL sh.mohitsingh.in/repo`"
fi

# No help from next launch
touch $HOME/.hushlogin

doing "Installing pure prompt..."

# cleanup old prompt files
if [[ -x $FUNPATH/prompt_pure_setup && -x $FUNPATH/async ]]; then
  rm -f $FUNPATH/prompt_pure_setup
  rm -f $FUNPATH/async
fi

# install pure prompt
curl https://raw.githubusercontent.com/sindresorhus/pure/master/pure.zsh --create-dirs -fsSLo $FUNPATH/prompt_pure_setup
curl https://raw.githubusercontent.com/sindresorhus/pure/master/async.zsh -fsSLo $FUNPATH/async
chmod +x $FUNPATH/prompt_pure_setup
chmod +x $FUNPATH/async
success

# Install custom completions
doing "Installing completions..."
if [[ -x $FUNPATH/_repo ]]; then
  rm -f $FUNPATH/_repo
fi
ln -s "$DOTLOC/completions/_repo" $FUNPATH/_repo
success

# link required files
doing "Linking zsh + git + tmux configs..."
for file in zshrc zshenv gitconfig gitignore tmux.conf
do
  rm "$HOME/.$file" &>/dev/null
  ln -s "$DOTLOC/$file" "$HOME/.$file"
done
success

# setup nvim
doing "Linking nvim config..."
mkdir -p "$HOME/.config/nvim"
for file in coc-settings.json init.vim
do
  rm "$HOME/.config/nvim/$file" &>/dev/null
  ln -s "$DOTLOC/$file" "$HOME/.config/nvim/$file"
done
success

# Install coc extensions
doing "Installing coc extensions...\\n"

if [[ ! -d $COC_EXT_PATH ]]; then
  mkdir -p "$HOME/.config/coc/extensions"
fi

cd "$HOME/.config/coc/extensions"

if [[ ! -f package.json ]]; then
  echo '{"dependencies":{}}'> package.json
fi

# coc extensions I use
coc_extensions=(
  \ coc-json
  \ coc-css
  \ coc-python
  \ coc-vimlsp
  \ coc-html
  \ coc-tsserver
  \ coc-snippets
  \ coc-eslint
  \ coc-prettier
  \ coc-git
  \ coc-yaml
  \ coc-lists
  \ coc-svg
  \ coc-dictionary
  \ coc-emoji
  \ )

flags="--global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod"

for ext in ${coc_extensions[*]};
do
  printf "\\033[2m      Installing %s\\033[0m" "$ext"
  npm install $flags $ext &>/dev/null
  # clear current line
  printf "\\r\\033[K"
done
# move cursor to end of previous line
printf "\\033[1A\\033[32C"
success

# change default shell to zsh
chsh -s zsh
