#!/usr/bin/env bash

# define variables
FUNPATH=/usr/local/share/zsh/site-functions
DOTLOC="$HOME/Projects/dotfiles"

# Include utilities
source /dev/stdin <<< "`curl -fsSL sh.mohitsingh.in/_utils`"

# Install dotfiles if not found
if [[ ! -d $DOTLOC ]]; then
  source /dev/stdin <<< "`curl -fsSL sh.mohitsingh.in/repo`"
fi

# No help from next launch
touch $HOME/.hushlogin

doing "Installing pure prompt..."

# cleanup old prompt files
if [[ -x $FUNPATH/prompt_pure_setup && -x $FUNPATH/async ]]; then
  rm -f $FUNPATH/prompt_pure_setup
  rm -f $FUNPATH/async
fi

# install pure prompt
curl https://raw.githubusercontent.com/sindresorhus/pure/master/pure.zsh --create-dirs -fsSLo $FUNPATH/prompt_pure_setup
curl https://raw.githubusercontent.com/sindresorhus/pure/master/async.zsh -fsSLo $FUNPATH/async
chmod +x $FUNPATH/prompt_pure_setup
chmod +x $FUNPATH/async
success

# Install custom completions
doing "Installing completions..."
if [[ -x $FUNPATH/_repo ]]; then
  rm -f $FUNPATH/_repo
fi
ln -s "$DOTLOC/completions/_repo" $FUNPATH/_repo
success

# link required files
doing "Linking zsh + git + tmux configs..."
for file in zshrc zshenv gitconfig gitignore tmux.conf
do
  rm "$HOME/.$file" &>/dev/null
  ln -s "$DOTLOC/$file" "$HOME/.$file"
done
success

# setup nvim
doing "Linking nvim config..."
mkdir -p "$HOME/.config/nvim"
for file in coc-settings.json init.vim
do
  rm "$HOME/.config/nvim/$file" &>/dev/null
  ln -s "$DOTLOC/$file" "$HOME/.config/nvim/$file"
done
success

# change default shell to zsh
chsh -s zsh
