#!/bin/bash
# Setup zsh with plugins and prompts
#
# Usage: curl -fsSL sh.mohitsingh.in/shell | bash

# Make sure that following packages are already installed
# zsh, zsh-syntax-highlighting, zsh-autosuggestons

source /dev/stdin <<<"$(curl -fsSL sh.mohitsingh.in/_utils)"

# Install dotfiles if not found
DOTLOC="$HOME/Projects/dotfiles"
if [[ ! -d $DOTLOC ]]; then
	source /dev/stdin <<<"$(curl -fsSL sh.mohitsingh.in/repo)"
fi

# No help from next launch
touch "$HOME/.hushlogin"

# link required files
doing "Linking zsh + git + tmux configs..."
for file in "$DOTLOC"/{zsh,git,tmux}/*; do
	filename=$(basename "$file")
	[[ -e "$HOME/.$filename" ]] && rm "$HOME/.$filename" &>/dev/null
	ln -s "$file" "$HOME/.$filename"
done

# setup nvim config
NVIM_CONF="$HOME/.config"
doing "Linking nvim config..."
if [[ ! -d "$NVIM_CONF" ]]; then
	mkdir -p "$NVIM_CONF"
fi
ln -sf "$DOTLOC/nvim" "$NVIM_CONF/nvim"
success

# link other config
doing "Linking other configs..."
for file in "$DOTLOC"/config/*; do
	[[ -e "$HOME/.config/$file" ]] && rm -rf "$HOME/.config/$file" &>/dev/null
	ln -s "$DOTLOC/$file" "$HOME/.config/$file"
done

success
