#!/bin/bash
# Create new user
#
# Usage: curl -fsSL sh.mohitsingh.in/user | bash

echo -n "Name of user you want to create : "
read name </dev/tty
adduser --disabled-password --gecos '' $name
usermod -aG sudo $name
echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
cp -r .ssh /home/$name
chown -R $name:$name /home/$name/.ssh
