#!/bin/bash
# Setup neovim with coc and other plugins
#
# Usage: curl -fsSL sh.mohitsingh.in/vim | bash
#
# Make sure that neovim and nodejs are available

source /dev/stdin <<<"$(curl -fsSL sh.mohitsingh.in/_utils)"

# install dotfiles if not found
DOTLOC="$HOME/Projects/dotfiles"
if [[ ! -d $DOTLOC ]]; then
  source /dev/stdin <<<"$(curl -fsSL sh.mohitsingh.in/repo)"
fi

# setup nvim config
doing "Linking nvim config..."
mkdir -p "$HOME/.config/nvim"
for file in $DOTLOC/nvim/*; do
  target="$HOME/.config/nvim/$(basename $file)"
  [[ -e $target ]] && rm $target &>/dev/null
  ln -s $file $target
done
success

