#!/bin/bash
# Setup neovim with coc and other plugins
#
# Usage: curl -fsSL sh.mohitsingh.in/vim | bash
#
# Make sure that neovim and nodejs are available

source /dev/stdin <<<"$(curl -fsSL sh.mohitsingh.in/_utils)"

# install dotfiles if not found
DOTLOC="$HOME/Projects/dotfiles"
if [[ ! -d $DOTLOC ]]; then
	source /dev/stdin <<<"$(curl -fsSL sh.mohitsingh.in/repo)"
fi

# setup nvim config
NVIM_CONF="$HOME/.config"
doing "Linking nvim config..."
if [[ ! -d "$NVIM_CONF" ]]; then
	mkdir -p "$NVIM_CONF"
fi

# link nvim config
ln -sf "$DOTLOC/nvim" "$NVIM_CONF/nvim"
success

nvim +PlugInstall +qa
nvim +LSPInstall --sync +qa
