#!/usr/bin/env zsh

# for moving quickly
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias -- -="cd -"
alias ~="cd ~"
alias p="cd ~/Projects"

# Use clipboard for xclip
alias xclip="xclip -selection clipboard"

# download with aria2 using 16 connections
alias a2c="aria2c -x16 -s16"

# make nested directories
alias mkdir="mkdir -p"

# alias for tools
alias g="git"
alias vi="nvim"
alias vim="nvim"
alias py="python"
alias a="apt"
alias af="apt-fast"
alias c="cargo"
alias d="docker"
alias k="kubectl"
alias hf="hyperfine"
alias rs="rustc -C opt-level=z -C strip=symbols"

# better ls output using exa
alias la="exa -la --group-directories-first"
alias ll="exa -l --group-directories-first"
alias ls="exa"

# yarn shortcuts
alias yi="yarn"
alias ya="yarn add"
alias yd="yarn add --dev"
alias yr="yarn remove"
alias yu="yarn upgrade-interactive --latest"

# npm global alias
alias npmg="sudo npm -g"

# docker and swarm aliases
alias dbuild="docker buildx b"
alias dslogs="docker service logs -f"
alias dsrm="docker service rm"
alias dsps="docker service ps"
alias dsls="docker service ls"
alias dsll="docker stack ps"
alias dsup="docker stack deploy -c"
alias dsdown="docker stack rm"

# sudoed aliases, shell reloading and pretty paths
alias sudo="sudo "
alias reload="exec $SHELL -l"
alias path="echo -e ${PATH//:/\\\n}"

