fpath=("$HOME/.zsh" $fpath)

autoload -Uz compinit
compinit
autoload -Uz promptinit
promptinit

eval "$(starship init zsh)"

# enable zsh syntax highlighting, autosuggestions and fzf
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/fzf/key-bindings.zsh

export GOROOT="/usr/lib/go"
export GOPATH="$HOME/.go"
export CARGOPATH="$HOME/.cargo"
export RUSTC_WRAPPER=sccache
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
--layout=reverse \
--color=fg:#c0caf5,bg:#24283b,hl:#ff9e64 \
--color=fg+:#c0caf5,bg+:#292e42,hl+:#ff9e64 \
--color=info:#7aa2f7,prompt:#7dcfff,pointer:#7dcfff \
--color=marker:#9ece6a,spinner:#9ece6a,header:#9ece6a"

# create required directories for go
test -d "${GOPATH}" || mkdir "${GOPATH}" &>/dev/null
test -d "${GOPATH}/src/github.com" || mkdir -p "${GOPATH}/src/github.com" &>/dev/null

# Add rust and go to path
export PATH="$CARGOPATH/bin:$GOROOT/bin:$GOPATH/bin:$HOME/.local/bin:$PATH"

export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

zstyle ':completion:*' menu select

eval "$(repo sh)"
export DIRENV_LOG_FORMAT=
eval "$(direnv hook zsh)"

export HISTFILE=~/.hist
export HISTSIZE=10000
export SAVEHIST=10000
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt INC_APPEND_HISTORY_TIME 
setopt EXTENDED_HISTORY
