fpath=("$HOME/.zsh" $fpath)

autoload -Uz compinit
compinit
autoload -Uz promptinit
promptinit

eval "$(starship init zsh)"

# enable zsh syntax highlighting and autosuggestions
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh

export GOROOT="/usr/local/go"
export GOPATH="$HOME/.go"
export CARGOPATH="$HOME/.cargo"
export RUSTC_WRAPPER=sccache

# create required directories for go
test -d "${GOPATH}" || mkdir "${GOPATH}" &>/dev/null
test -d "${GOPATH}/src/github.com" || mkdir -p "${GOPATH}/src/github.com" &>/dev/null

# Add rust and go to path
export PATH="$CARGOPATH/bin:$GOROOT/bin:$GOPATH/bin:$HOME/.local/bin:$PATH"

export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

zstyle ':completion:*' menu select

eval "$(repo sh)"

export HISTFILE=~/.hist
export HISTSIZE=10000
export SAVEHIST=10000
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt INC_APPEND_HISTORY_TIME 
setopt EXTENDED_HISTORY
